name: Scheduled Job

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  scheduled-job:
    runs-on: windows-latest
    steps:
      - name: Execute Python script # Run the Testing3.py
        run: python Testing3.py
